---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hipster-shop-front
  namespace: hipster-shop
  labels:
    app: frontend
  annotations:
    #certmanager.k8s.io/acme-challenge-type: http01
    #certmanager.k8s.io/cluster-issuer: letsencrypt-production
    #ingress.kubernetes.io/proxy-body-size: "0"
    kubernetes.io/ingress.class: nginx
    #kubernetes.io/tls-acme: "true"
    #nginx.ingress.kubernetes.io/proxy-body-size: "0"
    #ingress.kubernetes.io/ssl-redirect: "true"
    #nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: shop.35.228.23.197.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
  #tls:
  #- hosts:
  #  - shop.35.228.23.197.nip.io
  #  secretName: shop.35.228.23.197.nip.io
