apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: dev-veiw-ken
    namespace: dev
subjects:
- kind: ServiceAccount
  name: ken
  namespace: dev
roleRef:
    kind: ClusterRole
    name: view
    apiGroup: rbac.authorization.k8s.io
