apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: storage-pod
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - mountPath: "/data"
        name: storage-for-nginx
  volumes:
    - name: storage-for-nginx
      persistentVolumeClaim:
        claimName: storage-pvc
