apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: monitoring
  labels:
    app: nginx-service
    prometheus: default
spec:
  selector:
    app: nginx-mon
  type: ClusterIP
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
    - name: metrics
      protocol: TCP
      port: 9113
      targetPort: 9113
