apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-rru
  labels:
    app: paymentservice-rru
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: paymentservice-rru
  template:
    metadata:
      labels:
        app: paymentservice-rru
    spec:
      containers:
      - name: server
        image: yellowboy/hs-paymentservice:0.0.2
